version: '3.8'

services:
  insightscape:
    container_name: insight_scape
    image: insightscape
    command: >
      bash -c "uvicorn app.main:app --reload --host 0.0.0.0 --port $PORT"
    
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "$PORT:$PORT"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/venv
    depends_on:
      - db
  db:
    image: postgres
    container_name: insight_scape_postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "$DB_PORT:$DB_PORT"
    volumes:
      - ./bin:/docker-entrypoint-bin.d
